# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /skarab/projetos/skarab-gbe-control/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5.xci
# IP: The module: 'ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /skarab/projetos/skarab-gbe-control/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /skarab/projetos/skarab-gbe-control/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5.xci
# IP: The module: 'ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /skarab/projetos/skarab-gbe-control/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5/ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_c_counter_binary_v12_0_i5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
