// AUTOMATICALLY GENERATED BY PYTHON
    // Please do not commit this file into git 

    module wbs_master_arbiter #(
        parameter N_SLAVES   = 7,
        parameter N_SUB_ARBS = 4,
        parameter SLAVE_ADDR   = 0,
        parameter SLAVE_HIGH   = 0,
        parameter TIMEOUT      = 10
      ) (
        input  wb_clk_i, wb_rst_i,
    
        input             wbm_cyc_i,
        input             wbm_stb_i,
        input             wbm_we_i,
        input       [3:0] wbm_sel_i,
        input      [31:0] wbm_adr_i,
        input      [31:0] wbm_dat_i,
        output     [31:0] wbm_dat_o,
        output            wbm_ack_o,
        output            wbm_err_o,
    
        output     [N_SLAVES - 1:0] wbs_cyc_o,
        output     [N_SLAVES - 1:0] wbs_stb_o,
        output                        wbs_we_o,
        output                  [3:0] wbs_sel_o,
        output  [N_SUB_ARBS*32-1:0] wbs_adr_o,
        output                 [31:0] wbs_dat_o,
        input   [N_SLAVES*32 - 1:0] wbs_dat_i,
        input   [N_SLAVES    - 1:0] wbs_ack_i,
        input   [N_SLAVES    - 1:0] wbs_err_i
      );
    
  localparam SUBARB_0 = 0;
  localparam SUBARB_1 = 1;

  localparam N_SLAVES_ARB0 = 32;
  localparam N_SLAVES_ARB1 = 11;

  localparam SLAVE_ADDR_ARB0 = { 32'h801a0060 - 32'h800dc000,//pkt_ctrs_compare1_ss_status
32'h801a005c - 32'h800dc000,//pkt_ctrs_compare1_ss_ctrl
32'h801a0058 - 32'h800dc000,//pkt_ctrs1_ss_status
32'h801a0054 - 32'h800dc000,//pkt_ctrs1_ss_ctrl
32'h801a0050 - 32'h800dc000,//fir_filter_snapshoot_ila_status
32'h801a004c - 32'h800dc000,//fir_filter_snapshoot_ila_ctrl
32'h801a0048 - 32'h800dc000,//err_walk1
32'h801a0044 - 32'h800dc000,//err_valid_raw1
32'h801a0040 - 32'h800dc000,//err_ramp1
32'h801a003c - 32'h800dc000,//err_pkt_ctr_step1
32'h801a0038 - 32'h800dc000,//err_pkt_ctr1
32'h801a0034 - 32'h800dc000,//err_marker1
32'h801a0030 - 32'h800dc000,//dec_factor
32'h801a002c - 32'h800dc000,//debug_rx_data_mem_gbe
32'h801a0028 - 32'h800dc000,//debug_rx_data_mem_fifo
32'h801a0024 - 32'h800dc000,//data_rx_valmir
32'h801a0020 - 32'h800dc000,//d5_ss_status
32'h801a001c - 32'h800dc000,//d5_ss_ctrl
32'h801a0018 - 32'h800dc000,//d4_ss_status
32'h801a0014 - 32'h800dc000,//d4_ss_ctrl
32'h801a0010 - 32'h800dc000,//d3_ss_status
32'h801a000c - 32'h800dc000,//d3_ss_ctrl
32'h801a0008 - 32'h800dc000,//clk_mhz
32'h801a0004 - 32'h800dc000,//addr_data_gbe
32'h801a0000 - 32'h800dc000,//addr_data_fifo
32'h80190000 - 32'h800dc000,//pkt_ctrs_compare1_ss_bram
32'h80150000 - 32'h800dc000,//pkt_ctrs1_ss_bram
32'h8014c000 - 32'h800dc000,//fir_filter_snapshoot_ila_bram
32'h8012c000 - 32'h800dc000,//d5_ss_bram
32'h8010c000 - 32'h800dc000,//d4_ss_bram
32'h800ec000 - 32'h800dc000,//d3_ss_bram
32'h800dc000 - 32'h800dc000}; //tx_one_gbe
  localparam SLAVE_HIGH_ARB0 = { 32'h801a0063 - 32'h800dc000,//pkt_ctrs_compare1_ss_status
32'h801a005f - 32'h800dc000,//pkt_ctrs_compare1_ss_ctrl
32'h801a005b - 32'h800dc000,//pkt_ctrs1_ss_status
32'h801a0057 - 32'h800dc000,//pkt_ctrs1_ss_ctrl
32'h801a0053 - 32'h800dc000,//fir_filter_snapshoot_ila_status
32'h801a004f - 32'h800dc000,//fir_filter_snapshoot_ila_ctrl
32'h801a004b - 32'h800dc000,//err_walk1
32'h801a0047 - 32'h800dc000,//err_valid_raw1
32'h801a0043 - 32'h800dc000,//err_ramp1
32'h801a003f - 32'h800dc000,//err_pkt_ctr_step1
32'h801a003b - 32'h800dc000,//err_pkt_ctr1
32'h801a0037 - 32'h800dc000,//err_marker1
32'h801a0033 - 32'h800dc000,//dec_factor
32'h801a002f - 32'h800dc000,//debug_rx_data_mem_gbe
32'h801a002b - 32'h800dc000,//debug_rx_data_mem_fifo
32'h801a0027 - 32'h800dc000,//data_rx_valmir
32'h801a0023 - 32'h800dc000,//d5_ss_status
32'h801a001f - 32'h800dc000,//d5_ss_ctrl
32'h801a001b - 32'h800dc000,//d4_ss_status
32'h801a0017 - 32'h800dc000,//d4_ss_ctrl
32'h801a0013 - 32'h800dc000,//d3_ss_status
32'h801a000f - 32'h800dc000,//d3_ss_ctrl
32'h801a000b - 32'h800dc000,//clk_mhz
32'h801a0007 - 32'h800dc000,//addr_data_gbe
32'h801a0003 - 32'h800dc000,//addr_data_fifo
32'h8019ffff - 32'h800dc000,//pkt_ctrs_compare1_ss_bram
32'h8018ffff - 32'h800dc000,//pkt_ctrs1_ss_bram
32'h8014ffff - 32'h800dc000,//fir_filter_snapshoot_ila_bram
32'h8014bfff - 32'h800dc000,//d5_ss_bram
32'h8012bfff - 32'h800dc000,//d4_ss_bram
32'h8010bfff - 32'h800dc000,//d3_ss_bram
32'h800ebfff - 32'h800dc000}; //tx_one_gbe
  localparam SLAVE_ADDR_ARB1 = { 32'h801a008c - 32'h801a0064,//sys_block
32'h801a0088 - 32'h801a0064,//vaild_rx_valmir1
32'h801a0084 - 32'h801a0064,//tx_overflow1
32'h801a0080 - 32'h801a0064,//tx_control
32'h801a007c - 32'h801a0064,//tx_afull1
32'h801a0078 - 32'h801a0064,//rx_valid1
32'h801a0074 - 32'h801a0064,//rx_overrun1
32'h801a0070 - 32'h801a0064,//rx_eof1
32'h801a006c - 32'h801a0064,//rx_control1
32'h801a0068 - 32'h801a0064,//rx_badframe1
32'h801a0064 - 32'h801a0064}; //read_gbe_or_fifo
  localparam SLAVE_HIGH_ARB1 = { 32'h801a00ab - 32'h801a0064,//sys_block
32'h801a008b - 32'h801a0064,//vaild_rx_valmir1
32'h801a0087 - 32'h801a0064,//tx_overflow1
32'h801a0083 - 32'h801a0064,//tx_control
32'h801a007f - 32'h801a0064,//tx_afull1
32'h801a007b - 32'h801a0064,//rx_valid1
32'h801a0077 - 32'h801a0064,//rx_overrun1
32'h801a0073 - 32'h801a0064,//rx_eof1
32'h801a006f - 32'h801a0064,//rx_control1
32'h801a006b - 32'h801a0064,//rx_badframe1
32'h801a0067 - 32'h801a0064}; //read_gbe_or_fifo

  wire     [N_SUB_ARBS - 1:0] wb_cyc_o;
      wire     [N_SUB_ARBS - 1:0] wb_stb_o;
      wire                          wb_we_o;
      wire                    [3:0] wb_sel_o;
      wire                   [31:0] wb_adr_o;
      wire                   [31:0] wb_dat_o;
      wire  [N_SUB_ARBS*32 - 1:0] wb_dat_i;
      wire  [N_SUB_ARBS    - 1:0] wb_ack_i;
      wire  [N_SUB_ARBS    - 1:0] wb_err_i;

  wire     [N_SLAVES_ARB0 - 1:0] wbs_cyc_o_arb0;
      wire     [N_SLAVES_ARB0 - 1:0] wbs_stb_o_arb0;
      wire                             wbs_we_o_arb0;
      wire                       [3:0] wbs_sel_o_arb0;
      wire                      [31:0] wbs_adr_o_arb0;
      wire                      [31:0] wbs_dat_o_arb0;
      wire  [N_SLAVES_ARB0*32 - 1:0] wbs_dat_i_arb0;
      wire  [N_SLAVES_ARB0    - 1:0] wbs_ack_i_arb0;
      wire  [N_SLAVES_ARB0    - 1:0] wbs_err_i_arb0;


  wire     [N_SLAVES_ARB1 - 1:0] wbs_cyc_o_arb1;
      wire     [N_SLAVES_ARB1 - 1:0] wbs_stb_o_arb1;
      wire                             wbs_we_o_arb1;
      wire                       [3:0] wbs_sel_o_arb1;
      wire                      [31:0] wbs_adr_o_arb1;
      wire                      [31:0] wbs_dat_o_arb1;
      wire  [N_SLAVES_ARB1*32 - 1:0] wbs_dat_i_arb1;
      wire  [N_SLAVES_ARB1    - 1:0] wbs_ack_i_arb1;
      wire  [N_SLAVES_ARB1    - 1:0] wbs_err_i_arb1;

  assign wbs_cyc_o = {wbs_cyc_o_arb1, wbs_cyc_o_arb0};
  assign wbs_stb_o = {wbs_stb_o_arb1, wbs_stb_o_arb0};
  assign wbs_we_o = {wbs_we_o_arb1, wbs_we_o_arb0};
  assign wbs_sel_o = {wbs_sel_o_arb1, wbs_sel_o_arb0};
  assign wbs_adr_o = {wbs_adr_o_arb1, wbs_adr_o_arb0};
  assign wbs_dat_o = {wbs_dat_o_arb1, wbs_dat_o_arb0};
  assign {wbs_dat_i_arb1, wbs_dat_i_arb0} = wbs_dat_i;
  assign {wbs_ack_i_arb1, wbs_ack_i_arb0} = wbs_ack_i;
  assign {wbs_err_i_arb1, wbs_err_i_arb0} = wbs_err_i;

  wbs_arbiter #(
        .N_SLAVES(N_SUB_ARBS),
        .SLAVE_ADDR(SLAVE_ADDR),
        .SLAVE_HIGH(SLAVE_HIGH),
        .TIMEOUT(1024)
      ) wbs_arbiter_primary (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_ack_o(wbm_ack_o),
        .wbm_adr_i(wbm_adr_i),
        .wbm_cyc_i(wbm_cyc_i),
        .wbm_dat_o(wbm_dat_o),
        .wbm_we_i ( wbm_we_i),
        .wbm_dat_i(wbm_dat_i),
        .wbm_sel_i(wbm_sel_i),
        .wbm_stb_i(wbm_stb_i),
        .wbm_err_o(wbm_err_o),
    
        .wbs_cyc_o(wb_cyc_o),
        .wbs_ack_i(wb_ack_i),
        .wbs_err_i(wb_err_i),
        .wbs_dat_i(wb_dat_i),
        .wbs_stb_o(wb_stb_o),
        .wbs_we_o ( wb_we_o),
        .wbs_sel_o(wb_sel_o),
        .wbs_dat_o(wb_dat_o),
        .wbs_adr_o(wb_adr_o)
      );

  wbs_arbiter #(
        .N_SLAVES(N_SLAVES_ARB0),
        .SLAVE_ADDR(SLAVE_ADDR_ARB0),
        .SLAVE_HIGH(SLAVE_HIGH_ARB0),
        .TIMEOUT(1024)
      ) wbs_arbiter_0 (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_we_i (wb_we_o),
        .wbm_sel_i(wb_sel_o),
        .wbm_ack_o(wb_ack_i[SUBARB_0]),
        .wbm_err_o(wb_err_i[SUBARB_0]),
        .wbm_stb_i(wb_stb_o[SUBARB_0]),
        .wbm_cyc_i(wb_cyc_o[SUBARB_0]),
        .wbm_dat_i(wb_dat_o),
        .wbm_dat_o(wb_dat_i[(SUBARB_0+1)*32-1:(SUBARB_0)*32]),
        .wbm_adr_i(wb_adr_o),
    
        .wbs_adr_o(wbs_adr_o_arb0),
        .wbs_cyc_o(wbs_cyc_o_arb0),
        .wbs_ack_i(wbs_ack_i_arb0),
        .wbs_err_i(wbs_err_i_arb0),
        .wbs_dat_i(wbs_dat_i_arb0),
        .wbs_stb_o(wbs_stb_o_arb0),
        .wbs_we_o ( wbs_we_o_arb0),
        .wbs_sel_o(wbs_sel_o_arb0),
        .wbs_dat_o(wbs_dat_o_arb0)
      );


  wbs_arbiter #(
        .N_SLAVES(N_SLAVES_ARB1),
        .SLAVE_ADDR(SLAVE_ADDR_ARB1),
        .SLAVE_HIGH(SLAVE_HIGH_ARB1),
        .TIMEOUT(1024)
      ) wbs_arbiter_1 (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_we_i (wb_we_o),
        .wbm_sel_i(wb_sel_o),
        .wbm_ack_o(wb_ack_i[SUBARB_1]),
        .wbm_err_o(wb_err_i[SUBARB_1]),
        .wbm_stb_i(wb_stb_o[SUBARB_1]),
        .wbm_cyc_i(wb_cyc_o[SUBARB_1]),
        .wbm_dat_i(wb_dat_o),
        .wbm_dat_o(wb_dat_i[(SUBARB_1+1)*32-1:(SUBARB_1)*32]),
        .wbm_adr_i(wb_adr_o),
    
        .wbs_adr_o(wbs_adr_o_arb1),
        .wbs_cyc_o(wbs_cyc_o_arb1),
        .wbs_ack_i(wbs_ack_i_arb1),
        .wbs_err_i(wbs_err_i_arb1),
        .wbs_dat_i(wbs_dat_i_arb1),
        .wbs_stb_o(wbs_stb_o_arb1),
        .wbs_we_o ( wbs_we_o_arb1),
        .wbs_sel_o(wbs_sel_o_arb1),
        .wbs_dat_o(wbs_dat_o_arb1)
      );

endmodule