
function control_axi_stream_gbe_config(this_block)

  % Revision History:
  %
  %   22-Jul-2026  (14:02 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/control_axi_stream_gbe.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('control_axi_stream_gbe');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('a_sync_nrst');
  this_block.addSimulinkInport('rx_valid');
  this_block.addSimulinkInport('rx_data');
  this_block.addSimulinkInport('tx_pkt_len');
  this_block.addSimulinkInport('s_axis_tvalid');
  this_block.addSimulinkInport('s_axis_tdata');
  this_block.addSimulinkInport('s_axis_tlast');
  this_block.addSimulinkInport('m_axis_tready');
  this_block.addSimulinkInport('debug_addr_data_gbe');
  this_block.addSimulinkInport('debug_addr_data_fifo');
  this_block.addSimulinkInport('debug_read_gbe_or_fifo');
  this_block.addSimulinkInport('decim_factor');
  

  this_block.addSimulinkOutport('tx_data');
  this_block.addSimulinkOutport('tx_val');
  this_block.addSimulinkOutport('tx_eof');
  this_block.addSimulinkOutport('s_axis_tready');
  this_block.addSimulinkOutport('m_axis_tvalid');
  this_block.addSimulinkOutport('m_axis_tdata');
  this_block.addSimulinkOutport('m_axis_tlast');
  this_block.addSimulinkOutport('debug_rx_data_mem_gbe');
  this_block.addSimulinkOutport('debug_rx_data_mem_fifo');

  tx_data_port = this_block.port('tx_data');
  tx_data_port.setType('UFix_8_0');
  tx_val_port = this_block.port('tx_val');
  tx_val_port.setType('UFix_1_0');
  tx_val_port.useHDLVector(false);
  tx_eof_port = this_block.port('tx_eof');
  tx_eof_port.setType('UFix_1_0');
  tx_eof_port.useHDLVector(false);
  s_axis_tready_port = this_block.port('s_axis_tready');
  s_axis_tready_port.setType('UFix_1_0');
  s_axis_tready_port.useHDLVector(false);
  m_axis_tvalid_port = this_block.port('m_axis_tvalid');
  m_axis_tvalid_port.setType('UFix_1_0');
  m_axis_tvalid_port.useHDLVector(false);
  m_axis_tdata_port = this_block.port('m_axis_tdata');
  m_axis_tdata_port.setType('UFix_64_0');
  m_axis_tlast_port = this_block.port('m_axis_tlast');
  m_axis_tlast_port.setType('UFix_1_0');
  m_axis_tlast_port.useHDLVector(false);
  debug_rx_data_mem_gbe_port = this_block.port('debug_rx_data_mem_gbe');
  debug_rx_data_mem_gbe_port.setType('UFix_8_0');
  debug_rx_data_mem_fifo_port = this_block.port('debug_rx_data_mem_fifo');
  debug_rx_data_mem_fifo_port.setType('UFix_8_0');


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.decim_factor

    if (this_block.port('a_sync_nrst').width ~= 1);
      this_block.setError('Input data type for port "a_sync_nrst" must have width=1.');
    end

    this_block.port('a_sync_nrst').useHDLVector(false);

    if (this_block.port('rx_valid').width ~= 1);
      this_block.setError('Input data type for port "rx_valid" must have width=1.');
    end

    this_block.port('rx_valid').useHDLVector(false);

    if (this_block.port('rx_data').width ~= 8);
      this_block.setError('Input data type for port "rx_data" must have width=8.');
    end

    if (this_block.port('tx_pkt_len').width ~= 16);
      this_block.setError('Input data type for port "tx_pkt_len" must have width=10.');
    end

    if (this_block.port('s_axis_tvalid').width ~= 1);
      this_block.setError('Input data type for port "s_axis_tvalid" must have width=1.');
    end

    this_block.port('s_axis_tvalid').useHDLVector(false);

    if (this_block.port('s_axis_tdata').width ~= 64);
      this_block.setError('Input data type for port "s_axis_tdata" must have width=64.');
    end

    if (this_block.port('s_axis_tlast').width ~= 1);
      this_block.setError('Input data type for port "s_axis_tlast" must have width=1.');
    end

    this_block.port('s_axis_tlast').useHDLVector(false);

    if (this_block.port('m_axis_tready').width ~= 1);
      this_block.setError('Input data type for port "m_axis_tready" must have width=1.');
    end

    this_block.port('m_axis_tready').useHDLVector(false);

    if (this_block.port('debug_addr_data_gbe').width ~= 8);
      this_block.setError('Input data type for port "debug_addr_data_gbe" must have width=8.');
    end

    if (this_block.port('debug_rx_data_mem_fifo').width ~= 8);
      this_block.setError('Input data type for port "debug_rx_data_mem_fifo" must have width=8.');
    end
    if (this_block.port('debug_read_gbe_or_fifo').width ~= 1);
      this_block.setError('Input data type for port "debug_rx_data_mem_fifo" must have width=1.');
    end
    
    if (this_block.port('decim_factor').width ~= 10);
      this_block.setError('Input data type for port "debug_rx_data_mem_fifo" must have width=1.');
    end

  end  % if(inputTypesKnown)decim_factor
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');

  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/cmd_sync_detector.v');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/serdes/deserializer.v');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/serdes/serializer.v');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/control_axi_stream_gbe.v');
    
  
  %this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/sync_fifo_peek.v')
  
  %this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/cmd_sync_detector.v');
  %f1 = this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/serdes/deserializer.sv');
  %f1.setFileType('SystemVerilog');
  
  %f2 = this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/serdes/serializer.sv');
  %f2.setFileType('SystemVerilog');
  
  %this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/control_axi_stream_gbe_checkpoint_fifos_serdes.v');
return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

