# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/fir_filter/fir_filter/myproj/myproj.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i1/fir_filter_c_counter_binary_v12_0_i1.xci
# IP: The module: 'fir_filter_c_counter_binary_v12_0_i1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/fir_filter/fir_filter/myproj/myproj.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i1/fir_filter_c_counter_binary_v12_0_i1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_c_counter_binary_v12_0_i1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/fir_filter/fir_filter/myproj/myproj.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i1/fir_filter_c_counter_binary_v12_0_i1.xci
# IP: The module: 'fir_filter_c_counter_binary_v12_0_i1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/fir_filter/fir_filter/myproj/myproj.srcs/sources_1/ip/fir_filter_c_counter_binary_v12_0_i1/fir_filter_c_counter_binary_v12_0_i1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_c_counter_binary_v12_0_i1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
