# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ethernet_one_gbe_skarab_loopback2/user_const.xdc

# XDC: imports/Constraints/soc_version.xdc

# IP: ip/cross_clock_fifo_wb_out_73x16/cross_clock_fifo_wb_out_73x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cross_clock_fifo_wb_out_73x16 || ORIG_REF_NAME==cross_clock_fifo_wb_out_73x16} -quiet] -quiet

# IP: ip/xadc_measurement/xadc_measurement.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_measurement || ORIG_REF_NAME==xadc_measurement} -quiet] -quiet

# IP: ip/isp_spi_buffer/isp_spi_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==isp_spi_buffer || ORIG_REF_NAME==isp_spi_buffer} -quiet] -quiet

# IP: ip/common_clock_fifo_32x16/common_clock_fifo_32x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==common_clock_fifo_32x16 || ORIG_REF_NAME==common_clock_fifo_32x16} -quiet] -quiet

# Block Designs: bd/cont_microblaze/cont_microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze || ORIG_REF_NAME==cont_microblaze} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_slave_wishbone_classic_master_0_0/cont_microblaze_axi_slave_wishbone_classic_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_slave_wishbone_classic_master_0_0 || ORIG_REF_NAME==cont_microblaze_axi_slave_wishbone_classic_master_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timebase_wdt_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timer_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timer_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==cont_microblaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_mdm_1_0 || ORIG_REF_NAME==cont_microblaze_mdm_1_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_periph_0/cont_microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_dlmb_bram_if_cntlr_0/cont_microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cont_microblaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_dlmb_v10_0/cont_microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_dlmb_v10_0 || ORIG_REF_NAME==cont_microblaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_ilmb_bram_if_cntlr_0/cont_microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cont_microblaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_ilmb_v10_0/cont_microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_ilmb_v10_0 || ORIG_REF_NAME==cont_microblaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_lmb_bram_0/cont_microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_lmb_bram_0 || ORIG_REF_NAME==cont_microblaze_lmb_bram_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_rst_Clk_100M_0 || ORIG_REF_NAME==cont_microblaze_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_xlconcat_0_0/cont_microblaze_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_xlconcat_0_0 || ORIG_REF_NAME==cont_microblaze_xlconcat_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_xbar_0/cont_microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_xbar_0 || ORIG_REF_NAME==cont_microblaze_xbar_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_auto_pc_0/cont_microblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_auto_pc_0 || ORIG_REF_NAME==cont_microblaze_auto_pc_0} -quiet] -quiet

# IP: ip/gmii_to_sgmii/gmii_to_sgmii.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_sgmii || ORIG_REF_NAME==gmii_to_sgmii} -quiet] -quiet

# IP: ip/packet_byte_count_fifo/packet_byte_count_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==packet_byte_count_fifo || ORIG_REF_NAME==packet_byte_count_fifo} -quiet] -quiet

# IP: ip/gmii_to_xaui_fifo/gmii_to_xaui_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_xaui_fifo || ORIG_REF_NAME==gmii_to_xaui_fifo} -quiet] -quiet

# IP: ip/xaui_to_gmii_fifo/xaui_to_gmii_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xaui_to_gmii_fifo || ORIG_REF_NAME==xaui_to_gmii_fifo} -quiet] -quiet

# IP: ip/rx_packet_fifo_bram/rx_packet_fifo_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_packet_fifo_bram || ORIG_REF_NAME==rx_packet_fifo_bram} -quiet] -quiet

# IP: ip/cpu_buffer/cpu_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_buffer || ORIG_REF_NAME==cpu_buffer} -quiet] -quiet

# IP: ip/rx_packet_ctrl_fifo/rx_packet_ctrl_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_packet_ctrl_fifo || ORIG_REF_NAME==rx_packet_ctrl_fifo} -quiet] -quiet

# IP: ip/tx_fifo_ext/tx_fifo_ext.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_fifo_ext || ORIG_REF_NAME==tx_fifo_ext} -quiet] -quiet

# IP: ip/tx_data_fifo_ext/tx_data_fifo_ext.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_data_fifo_ext || ORIG_REF_NAME==tx_data_fifo_ext} -quiet] -quiet

# IP: ip/tx_packet_ctrl_fifo/tx_packet_ctrl_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_packet_ctrl_fifo || ORIG_REF_NAME==tx_packet_ctrl_fifo} -quiet] -quiet

# IP: ip/tx_packet_fifo/tx_packet_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_packet_fifo || ORIG_REF_NAME==tx_packet_fifo} -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timebase_wdt_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timebase_wdt_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timer_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==cont_microblaze_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==cont_microblaze_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_mdm_1_0 || ORIG_REF_NAME==cont_microblaze_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0_ooc_trace.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0_ooc_debug.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_dlmb_v10_0/cont_microblaze_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_dlmb_v10_0 || ORIG_REF_NAME==cont_microblaze_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_ilmb_v10_0/cont_microblaze_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_ilmb_v10_0 || ORIG_REF_NAME==cont_microblaze_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_lmb_bram_0/cont_microblaze_lmb_bram_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_rst_Clk_100M_0 || ORIG_REF_NAME==cont_microblaze_rst_Clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cont_microblaze_rst_Clk_100M_0 || ORIG_REF_NAME==cont_microblaze_rst_Clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cont_microblaze/ip/cont_microblaze_xbar_0/cont_microblaze_xbar_0_ooc.xdc

# XDC: bd/cont_microblaze/ip/cont_microblaze_auto_pc_0/cont_microblaze_auto_pc_0_ooc.xdc

# XDC: bd/cont_microblaze/cont_microblaze_ooc.xdc
