// AUTOMATICALLY GENERATED BY PYTHON
    // Please do not commit this file into git 

    module wbs_master_arbiter #(
        parameter N_SLAVES   = 7,
        parameter N_SUB_ARBS = 4,
        parameter SLAVE_ADDR   = 0,
        parameter SLAVE_HIGH   = 0,
        parameter TIMEOUT      = 10
      ) (
        input  wb_clk_i, wb_rst_i,
    
        input             wbm_cyc_i,
        input             wbm_stb_i,
        input             wbm_we_i,
        input       [3:0] wbm_sel_i,
        input      [31:0] wbm_adr_i,
        input      [31:0] wbm_dat_i,
        output     [31:0] wbm_dat_o,
        output            wbm_ack_o,
        output            wbm_err_o,
    
        output     [N_SLAVES - 1:0] wbs_cyc_o,
        output     [N_SLAVES - 1:0] wbs_stb_o,
        output                        wbs_we_o,
        output                  [3:0] wbs_sel_o,
        output  [N_SUB_ARBS*32-1:0] wbs_adr_o,
        output                 [31:0] wbs_dat_o,
        input   [N_SLAVES*32 - 1:0] wbs_dat_i,
        input   [N_SLAVES    - 1:0] wbs_ack_i,
        input   [N_SLAVES    - 1:0] wbs_err_i
      );
    
  localparam SUBARB_0 = 0;
  localparam SUBARB_1 = 1;

  localparam N_SLAVES_ARB0 = 32;
  localparam N_SLAVES_ARB1 = 4;

  localparam SLAVE_ADDR_ARB0 = { 32'h8019c160 - 32'h800dc000,//rx_valid1
32'h8019c15c - 32'h800dc000,//rx_src_port
32'h8019c158 - 32'h800dc000,//rx_src_ip
32'h8019c154 - 32'h800dc000,//rx_overrun1
32'h8019c150 - 32'h800dc000,//rx_eof1
32'h8019c14c - 32'h800dc000,//rx_control1
32'h8019c148 - 32'h800dc000,//rx_badframe1
32'h8019c144 - 32'h800dc000,//pkt_ctrs_compare1_ss_status
32'h8019c140 - 32'h800dc000,//pkt_ctrs_compare1_ss_ctrl
32'h8019c13c - 32'h800dc000,//pkt_ctrs1_ss_status
32'h8019c138 - 32'h800dc000,//pkt_ctrs1_ss_ctrl
32'h8019c134 - 32'h800dc000,//err_walk1
32'h8019c130 - 32'h800dc000,//err_valid_raw1
32'h8019c12c - 32'h800dc000,//err_ramp1
32'h8019c128 - 32'h800dc000,//err_pkt_ctr_step1
32'h8019c124 - 32'h800dc000,//err_pkt_ctr1
32'h8019c120 - 32'h800dc000,//err_marker1
32'h8019c11c - 32'h800dc000,//data_rx_valmir
32'h8019c118 - 32'h800dc000,//d5_ss_status
32'h8019c114 - 32'h800dc000,//d5_ss_ctrl
32'h8019c110 - 32'h800dc000,//d4_ss_status
32'h8019c10c - 32'h800dc000,//d4_ss_ctrl
32'h8019c108 - 32'h800dc000,//d3_ss_status
32'h8019c104 - 32'h800dc000,//d3_ss_ctrl
32'h8019c100 - 32'h800dc000,//clk_mhz
32'h8019c000 - 32'h800dc000,//shared_bram
32'h8018c000 - 32'h800dc000,//pkt_ctrs_compare1_ss_bram
32'h8014c000 - 32'h800dc000,//pkt_ctrs1_ss_bram
32'h8012c000 - 32'h800dc000,//d5_ss_bram
32'h8010c000 - 32'h800dc000,//d4_ss_bram
32'h800ec000 - 32'h800dc000,//d3_ss_bram
32'h800dc000 - 32'h800dc000}; //tx_one_gbe
  localparam SLAVE_HIGH_ARB0 = { 32'h8019c163 - 32'h800dc000,//rx_valid1
32'h8019c15f - 32'h800dc000,//rx_src_port
32'h8019c15b - 32'h800dc000,//rx_src_ip
32'h8019c157 - 32'h800dc000,//rx_overrun1
32'h8019c153 - 32'h800dc000,//rx_eof1
32'h8019c14f - 32'h800dc000,//rx_control1
32'h8019c14b - 32'h800dc000,//rx_badframe1
32'h8019c147 - 32'h800dc000,//pkt_ctrs_compare1_ss_status
32'h8019c143 - 32'h800dc000,//pkt_ctrs_compare1_ss_ctrl
32'h8019c13f - 32'h800dc000,//pkt_ctrs1_ss_status
32'h8019c13b - 32'h800dc000,//pkt_ctrs1_ss_ctrl
32'h8019c137 - 32'h800dc000,//err_walk1
32'h8019c133 - 32'h800dc000,//err_valid_raw1
32'h8019c12f - 32'h800dc000,//err_ramp1
32'h8019c12b - 32'h800dc000,//err_pkt_ctr_step1
32'h8019c127 - 32'h800dc000,//err_pkt_ctr1
32'h8019c123 - 32'h800dc000,//err_marker1
32'h8019c11f - 32'h800dc000,//data_rx_valmir
32'h8019c11b - 32'h800dc000,//d5_ss_status
32'h8019c117 - 32'h800dc000,//d5_ss_ctrl
32'h8019c113 - 32'h800dc000,//d4_ss_status
32'h8019c10f - 32'h800dc000,//d4_ss_ctrl
32'h8019c10b - 32'h800dc000,//d3_ss_status
32'h8019c107 - 32'h800dc000,//d3_ss_ctrl
32'h8019c103 - 32'h800dc000,//clk_mhz
32'h8019c0ff - 32'h800dc000,//shared_bram
32'h8019bfff - 32'h800dc000,//pkt_ctrs_compare1_ss_bram
32'h8018bfff - 32'h800dc000,//pkt_ctrs1_ss_bram
32'h8014bfff - 32'h800dc000,//d5_ss_bram
32'h8012bfff - 32'h800dc000,//d4_ss_bram
32'h8010bfff - 32'h800dc000,//d3_ss_bram
32'h800ebfff - 32'h800dc000}; //tx_one_gbe
  localparam SLAVE_ADDR_ARB1 = { 32'h8019c170 - 32'h8019c164,//sys_block
32'h8019c16c - 32'h8019c164,//tx_overflow1
32'h8019c168 - 32'h8019c164,//tx_control
32'h8019c164 - 32'h8019c164}; //tx_afull1
  localparam SLAVE_HIGH_ARB1 = { 32'h8019c18f - 32'h8019c164,//sys_block
32'h8019c16f - 32'h8019c164,//tx_overflow1
32'h8019c16b - 32'h8019c164,//tx_control
32'h8019c167 - 32'h8019c164}; //tx_afull1

  wire     [N_SUB_ARBS - 1:0] wb_cyc_o;
      wire     [N_SUB_ARBS - 1:0] wb_stb_o;
      wire                          wb_we_o;
      wire                    [3:0] wb_sel_o;
      wire                   [31:0] wb_adr_o;
      wire                   [31:0] wb_dat_o;
      wire  [N_SUB_ARBS*32 - 1:0] wb_dat_i;
      wire  [N_SUB_ARBS    - 1:0] wb_ack_i;
      wire  [N_SUB_ARBS    - 1:0] wb_err_i;

  wire     [N_SLAVES_ARB0 - 1:0] wbs_cyc_o_arb0;
      wire     [N_SLAVES_ARB0 - 1:0] wbs_stb_o_arb0;
      wire                             wbs_we_o_arb0;
      wire                       [3:0] wbs_sel_o_arb0;
      wire                      [31:0] wbs_adr_o_arb0;
      wire                      [31:0] wbs_dat_o_arb0;
      wire  [N_SLAVES_ARB0*32 - 1:0] wbs_dat_i_arb0;
      wire  [N_SLAVES_ARB0    - 1:0] wbs_ack_i_arb0;
      wire  [N_SLAVES_ARB0    - 1:0] wbs_err_i_arb0;


  wire     [N_SLAVES_ARB1 - 1:0] wbs_cyc_o_arb1;
      wire     [N_SLAVES_ARB1 - 1:0] wbs_stb_o_arb1;
      wire                             wbs_we_o_arb1;
      wire                       [3:0] wbs_sel_o_arb1;
      wire                      [31:0] wbs_adr_o_arb1;
      wire                      [31:0] wbs_dat_o_arb1;
      wire  [N_SLAVES_ARB1*32 - 1:0] wbs_dat_i_arb1;
      wire  [N_SLAVES_ARB1    - 1:0] wbs_ack_i_arb1;
      wire  [N_SLAVES_ARB1    - 1:0] wbs_err_i_arb1;

  assign wbs_cyc_o = {wbs_cyc_o_arb1, wbs_cyc_o_arb0};
  assign wbs_stb_o = {wbs_stb_o_arb1, wbs_stb_o_arb0};
  assign wbs_we_o = {wbs_we_o_arb1, wbs_we_o_arb0};
  assign wbs_sel_o = {wbs_sel_o_arb1, wbs_sel_o_arb0};
  assign wbs_adr_o = {wbs_adr_o_arb1, wbs_adr_o_arb0};
  assign wbs_dat_o = {wbs_dat_o_arb1, wbs_dat_o_arb0};
  assign {wbs_dat_i_arb1, wbs_dat_i_arb0} = wbs_dat_i;
  assign {wbs_ack_i_arb1, wbs_ack_i_arb0} = wbs_ack_i;
  assign {wbs_err_i_arb1, wbs_err_i_arb0} = wbs_err_i;

  wbs_arbiter #(
        .N_SLAVES(N_SUB_ARBS),
        .SLAVE_ADDR(SLAVE_ADDR),
        .SLAVE_HIGH(SLAVE_HIGH),
        .TIMEOUT(1024)
      ) wbs_arbiter_primary (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_ack_o(wbm_ack_o),
        .wbm_adr_i(wbm_adr_i),
        .wbm_cyc_i(wbm_cyc_i),
        .wbm_dat_o(wbm_dat_o),
        .wbm_we_i ( wbm_we_i),
        .wbm_dat_i(wbm_dat_i),
        .wbm_sel_i(wbm_sel_i),
        .wbm_stb_i(wbm_stb_i),
        .wbm_err_o(wbm_err_o),
    
        .wbs_cyc_o(wb_cyc_o),
        .wbs_ack_i(wb_ack_i),
        .wbs_err_i(wb_err_i),
        .wbs_dat_i(wb_dat_i),
        .wbs_stb_o(wb_stb_o),
        .wbs_we_o ( wb_we_o),
        .wbs_sel_o(wb_sel_o),
        .wbs_dat_o(wb_dat_o),
        .wbs_adr_o(wb_adr_o)
      );

  wbs_arbiter #(
        .N_SLAVES(N_SLAVES_ARB0),
        .SLAVE_ADDR(SLAVE_ADDR_ARB0),
        .SLAVE_HIGH(SLAVE_HIGH_ARB0),
        .TIMEOUT(1024)
      ) wbs_arbiter_0 (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_we_i (wb_we_o),
        .wbm_sel_i(wb_sel_o),
        .wbm_ack_o(wb_ack_i[SUBARB_0]),
        .wbm_err_o(wb_err_i[SUBARB_0]),
        .wbm_stb_i(wb_stb_o[SUBARB_0]),
        .wbm_cyc_i(wb_cyc_o[SUBARB_0]),
        .wbm_dat_i(wb_dat_o),
        .wbm_dat_o(wb_dat_i[(SUBARB_0+1)*32-1:(SUBARB_0)*32]),
        .wbm_adr_i(wb_adr_o),
    
        .wbs_adr_o(wbs_adr_o_arb0),
        .wbs_cyc_o(wbs_cyc_o_arb0),
        .wbs_ack_i(wbs_ack_i_arb0),
        .wbs_err_i(wbs_err_i_arb0),
        .wbs_dat_i(wbs_dat_i_arb0),
        .wbs_stb_o(wbs_stb_o_arb0),
        .wbs_we_o ( wbs_we_o_arb0),
        .wbs_sel_o(wbs_sel_o_arb0),
        .wbs_dat_o(wbs_dat_o_arb0)
      );


  wbs_arbiter #(
        .N_SLAVES(N_SLAVES_ARB1),
        .SLAVE_ADDR(SLAVE_ADDR_ARB1),
        .SLAVE_HIGH(SLAVE_HIGH_ARB1),
        .TIMEOUT(1024)
      ) wbs_arbiter_1 (
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
    
        .wbm_we_i (wb_we_o),
        .wbm_sel_i(wb_sel_o),
        .wbm_ack_o(wb_ack_i[SUBARB_1]),
        .wbm_err_o(wb_err_i[SUBARB_1]),
        .wbm_stb_i(wb_stb_o[SUBARB_1]),
        .wbm_cyc_i(wb_cyc_o[SUBARB_1]),
        .wbm_dat_i(wb_dat_o),
        .wbm_dat_o(wb_dat_i[(SUBARB_1+1)*32-1:(SUBARB_1)*32]),
        .wbm_adr_i(wb_adr_o),
    
        .wbs_adr_o(wbs_adr_o_arb1),
        .wbs_cyc_o(wbs_cyc_o_arb1),
        .wbs_ack_i(wbs_ack_i_arb1),
        .wbs_err_i(wbs_err_i_arb1),
        .wbs_dat_i(wbs_dat_i_arb1),
        .wbs_stb_o(wbs_stb_o_arb1),
        .wbs_we_o ( wbs_we_o_arb1),
        .wbs_sel_o(wbs_sel_o_arb1),
        .wbs_dat_o(wbs_dat_o_arb1)
      );

endmodule