// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // onegbe: tx_one_gbe
    input ONE_GBE_MGTREFCLK_N,
    input ONE_GBE_MGTREFCLK_P,
    input ONE_GBE_SGMII_RX_N,
    input ONE_GBE_SGMII_RX_P,
    output ONE_GBE_RESET_N,
    output ONE_GBE_SGMII_TX_N,
    output ONE_GBE_SGMII_TX_P,
  // skarab: SKARAB
    input CONFIG_IO_2,
    input CONFIG_IO_5,
    input CPU_SUS_S3_N,
    input CPU_SUS_S4_N,
    input CPU_SUS_S5_N,
    input CPU_SUS_STAT_N,
    input DEBUG_UART_RX,
    input EMCCLK,
    input FAN_CONT_ALERT_N,
    input FAN_CONT_FAULT_N,
    input FLASH_WAIT,
    input FPGA_EMCCLK2,
    input FPGA_REFCLK_BUF0_N,
    input FPGA_REFCLK_BUF0_P,
    input FPGA_REFCLK_BUF1_N,
    input FPGA_REFCLK_BUF1_P,
    input FPGA_RESET_N,
    input MEZZANINE_0_FAULT_N,
    input MEZZANINE_0_INT_N,
    input MEZZANINE_0_PRESENT_N,
    input MEZZANINE_1_FAULT_N,
    input MEZZANINE_1_INT_N,
    input MEZZANINE_1_PRESENT_N,
    input MEZZANINE_2_FAULT_N,
    input MEZZANINE_2_INT_N,
    input MEZZANINE_2_PRESENT_N,
    input MEZZANINE_3_FAULT_N,
    input MEZZANINE_3_INT_N,
    input MEZZANINE_3_PRESENT_N,
    input MONITOR_ALERT_N,
    input ONE_GBE_INT_N,
    input ONE_GBE_LINK,
    input PCIE_RST_N,
    input SPI_MISO,
    input [3:0] USB_FPGA,
    input USB_I2C_CTRL,
    input USB_UART_TXD,
    inout [15:0] FLASH_DQ,
    inout I2C_SCL_FPGA,
    inout I2C_SDA_FPGA,
    inout MEZZANINE_0_ONE_WIRE,
    inout MEZZANINE_0_SCL_FPGA,
    inout MEZZANINE_0_SDA_FPGA,
    inout MEZZANINE_1_ONE_WIRE,
    inout MEZZANINE_1_SCL_FPGA,
    inout MEZZANINE_1_SDA_FPGA,
    inout MEZZANINE_2_ONE_WIRE,
    inout MEZZANINE_2_SCL_FPGA,
    inout MEZZANINE_2_SDA_FPGA,
    inout MEZZANINE_3_ONE_WIRE,
    inout MEZZANINE_3_SCL_FPGA,
    inout MEZZANINE_3_SDA_FPGA,
    inout ONE_WIRE_EEPROM,
    output CONFIG_IO_0,
    output CONFIG_IO_1,
    output CONFIG_IO_10,
    output CONFIG_IO_11,
    output CONFIG_IO_3,
    output CONFIG_IO_4,
    output CONFIG_IO_6,
    output CONFIG_IO_7,
    output CONFIG_IO_8,
    output CONFIG_IO_9,
    output CPU_PWR_BTN_N,
    output CPU_PWR_OK,
    output CPU_SYS_RESET_N,
    output DEBUG_UART_TX,
    output EMCCLK_FIX,
    output FAN_CONT_RST_N,
    output [28:0] FLASH_A,
    output FLASH_ADV_N,
    output FLASH_CS_N,
    output FLASH_OE_N,
    output FLASH_RS0,
    output FLASH_RS1,
    output FLASH_WE_N,
    output FPGA_ATX_PSU_KILL,
    output [7:0] FPGA_LEDS,
    output [15:0] GND,
    output I2C_RESET_FPGA,
    output MEZZANINE_0_ENABLE_N,
    output MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N,
    output MEZZANINE_1_ENABLE_N,
    output MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N,
    output MEZZANINE_2_ENABLE_N,
    output MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N,
    output MEZZANINE_3_CLK_SEL,
    output MEZZANINE_3_ENABLE_N,
    output MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N,
    output MEZZANINE_3_RESET,
    output MEZZANINE_COMBINED_FAULT,
    output ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N,
    output SPARTAN_CLK,
    output SPI_CLK,
    output SPI_CSB,
    output SPI_MOSI,
    output USB_UART_RXD
  );



  // usermodule: ethernet_one_gbe_skarab_axi
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0 = 6;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0 = 7;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0 = 8;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0 = 1;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0 = 9;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0 = 10;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0 = 2;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0 = 11;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0 = 12;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0 = 3;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0 = 13;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0 = 14;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0 = 15;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0 = 16;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0 = 17;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0 = 18;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0 = 19;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0 = 20;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0 = 21;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0 = 22;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0 = 23;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0 = 4;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0 = 24;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0 = 25;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0 = 5;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0 = 26;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0 = 27;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0 = 28;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0 = 29;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0 = 30;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0 = 31;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0 = 32;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0 = 33;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0 = 34;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0 = 35;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0 = 0;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0 = 36;
  localparam ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0 = 37;
  localparam N_SUB_ARBS = 2;
  localparam N_WB_SLAVES = 39;
  localparam SLAVE_ADDR = {
    32'h8019c068,
    32'h800dc000
    };
  localparam SLAVE_HIGH = {
    32'h8019c09f,
    32'h8019c067
    };
  localparam SYS_BLOCK_INST_WBID0 = 38;

/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // bram: d3/ss/bram
  wire [12:0] ethernet_one_gbe_skarab_axi_d3_ss_bram_addr;
  wire [127:0] ethernet_one_gbe_skarab_axi_d3_ss_bram_data_in;
  wire [127:0] ethernet_one_gbe_skarab_axi_d3_ss_bram_data_out;
  wire ethernet_one_gbe_skarab_axi_d3_ss_bram_we;
  // bram: d4/ss/bram
  wire [12:0] ethernet_one_gbe_skarab_axi_d4_ss_bram_addr;
  wire [127:0] ethernet_one_gbe_skarab_axi_d4_ss_bram_data_in;
  wire [127:0] ethernet_one_gbe_skarab_axi_d4_ss_bram_data_out;
  wire ethernet_one_gbe_skarab_axi_d4_ss_bram_we;
  // bram: d5/ss/bram
  wire [12:0] ethernet_one_gbe_skarab_axi_d5_ss_bram_addr;
  wire [127:0] ethernet_one_gbe_skarab_axi_d5_ss_bram_data_in;
  wire [127:0] ethernet_one_gbe_skarab_axi_d5_ss_bram_data_out;
  wire ethernet_one_gbe_skarab_axi_d5_ss_bram_we;
  // bram: pkt_ctrs1/ss/bram
  wire [15:0] ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_addr;
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_in;
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_out;
  wire ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_we;
  // bram: pkt_ctrs_compare1/ss/bram
  wire [12:0] ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_addr;
  wire [63:0] ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_in;
  wire [63:0] ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_out;
  wire ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_we;
  // onegbe: tx_one_gbe
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_ack;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_badframe;
  wire [7:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_data;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_dvld;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_eof;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_overrun;
  wire [31:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcip;
  wire [15:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcport;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_afull;
  wire [7:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_data;
  wire [31:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destip;
  wire [15:0] ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destport;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_dvld;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_eof;
  wire ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_overflow;
  wire gbe_if_present;
  wire gbe_link_up;
  wire gbe_status_vector;
  wire gmii_reset_done;
  wire host_reset_o;
  wire sync_gmii_fpga_rst;
  // skarab: SKARAB
  wire board_clk;
  wire board_clk_rst;
  wire [7:0] dsp_leds_i;
  wire fgbe_if_0_present;
  wire fgbe_if_1_present;
  wire fgbe_if_2_present;
  wire fgbe_if_3_present;
  wire fgbe_phy_rx_up_0;
  wire fgbe_phy_rx_up_1;
  wire fgbe_phy_rx_up_2;
  wire fgbe_phy_rx_up_3;
  wire gmii_clk;
  wire hmc_clk;
  wire hmc_rst;
  wire [2:0] mez0_id;
  wire mez0_init_done;
  wire mez0_post_ok;
  wire mez0_present;
  wire mez0_scl_in;
  wire mez0_scl_out;
  wire mez0_sda_in;
  wire mez0_sda_out;
  wire [2:0] mez1_id;
  wire mez1_init_done;
  wire mez1_post_ok;
  wire mez1_present;
  wire mez1_scl_in;
  wire mez1_scl_out;
  wire mez1_sda_in;
  wire mez1_sda_out;
  wire [2:0] mez2_id;
  wire mez2_init_done;
  wire mez2_post_ok;
  wire mez2_present;
  wire mez2_scl_in;
  wire mez2_scl_out;
  wire mez2_sda_in;
  wire mez2_sda_out;
  wire qsfp_soft_reset_0;
  wire qsfp_soft_reset_1;
  wire qsfp_soft_reset_2;
  wire qsfp_soft_reset_3;
  wire sys_clk;
  wire sys_rst;
  wire wb_clk_i;
  wire wb_rst_i;
  wire wbm_ack_i;
  wire [31:0] wbm_adr_o;
  wire wbm_cyc_o;
  wire [31:0] wbm_dat_i;
  wire [31:0] wbm_dat_o;
  wire [3:0] wbm_sel_o;
  wire wbm_stb_o;
  wire wbm_we_o;
  wire [1:0] xlgmii_rxled_0;
  wire [1:0] xlgmii_rxled_1;
  wire [1:0] xlgmii_rxled_2;
  wire [1:0] xlgmii_rxled_3;
  wire [1:0] xlgmii_txled_0;
  wire [1:0] xlgmii_txled_1;
  wire [1:0] xlgmii_txled_2;
  wire [1:0] xlgmii_txled_3;
  // sw_reg: addr_data_fifo
  wire [31:0] ethernet_one_gbe_skarab_axi_addr_data_fifo_user_data_out;
  // sw_reg: addr_data_gbe
  wire [31:0] ethernet_one_gbe_skarab_axi_addr_data_gbe_user_data_out;
  // sw_reg: clk_mhz
  wire [31:0] ethernet_one_gbe_skarab_axi_clk_mhz_user_data_in;
  // sw_reg: d3/ss/ctrl
  wire [31:0] ethernet_one_gbe_skarab_axi_d3_ss_ctrl_user_data_out;
  // sw_reg: d3/ss/status
  wire [31:0] ethernet_one_gbe_skarab_axi_d3_ss_status_user_data_in;
  // sw_reg: d4/ss/ctrl
  wire [31:0] ethernet_one_gbe_skarab_axi_d4_ss_ctrl_user_data_out;
  // sw_reg: d4/ss/status
  wire [31:0] ethernet_one_gbe_skarab_axi_d4_ss_status_user_data_in;
  // sw_reg: d5/ss/ctrl
  wire [31:0] ethernet_one_gbe_skarab_axi_d5_ss_ctrl_user_data_out;
  // sw_reg: d5/ss/status
  wire [31:0] ethernet_one_gbe_skarab_axi_d5_ss_status_user_data_in;
  // sw_reg: data_rx_valmir
  wire [31:0] ethernet_one_gbe_skarab_axi_data_rx_valmir_user_data_in;
  // sw_reg: debug_rx_data_mem_fifo
  wire [31:0] ethernet_one_gbe_skarab_axi_debug_rx_data_mem_fifo_user_data_in;
  // sw_reg: debug_rx_data_mem_gbe
  wire [31:0] ethernet_one_gbe_skarab_axi_debug_rx_data_mem_gbe_user_data_in;
  // sw_reg: err_marker1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_marker1_user_data_in;
  // sw_reg: err_pkt_ctr1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_pkt_ctr1_user_data_in;
  // sw_reg: err_pkt_ctr_step1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_pkt_ctr_step1_user_data_in;
  // sw_reg: err_ramp1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_ramp1_user_data_in;
  // sw_reg: err_valid_raw1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_valid_raw1_user_data_in;
  // sw_reg: err_walk1
  wire [31:0] ethernet_one_gbe_skarab_axi_err_walk1_user_data_in;
  // sw_reg: pkt_ctrs1/ss/ctrl
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_ctrl_user_data_out;
  // sw_reg: pkt_ctrs1/ss/status
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_status_user_data_in;
  // sw_reg: pkt_ctrs_compare1/ss/ctrl
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_ctrl_user_data_out;
  // sw_reg: pkt_ctrs_compare1/ss/status
  wire [31:0] ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_status_user_data_in;
  // sw_reg: read_gbe_or_fifo
  wire [31:0] ethernet_one_gbe_skarab_axi_read_gbe_or_fifo_user_data_out;
  // sw_reg: rx_badframe1
  wire [31:0] ethernet_one_gbe_skarab_axi_rx_badframe1_user_data_in;
  // sw_reg: rx_control1
  wire [31:0] ethernet_one_gbe_skarab_axi_rx_control1_user_data_out;
  // sw_reg: rx_eof1
  wire [31:0] ethernet_one_gbe_skarab_axi_rx_eof1_user_data_in;
  // sw_reg: rx_overrun1
  wire [31:0] ethernet_one_gbe_skarab_axi_rx_overrun1_user_data_in;
  // sw_reg: rx_valid1
  wire [31:0] ethernet_one_gbe_skarab_axi_rx_valid1_user_data_in;
  // sw_reg: tx_afull1
  wire [31:0] ethernet_one_gbe_skarab_axi_tx_afull1_user_data_in;
  // sw_reg: tx_control
  wire [31:0] ethernet_one_gbe_skarab_axi_tx_control_user_data_out;
  // sw_reg: tx_overflow1
  wire [31:0] ethernet_one_gbe_skarab_axi_tx_overflow1_user_data_in;
  // sw_reg: vaild_rx_valmir1
  wire [31:0] ethernet_one_gbe_skarab_axi_vaild_rx_valmir1_user_data_in;
  // usermodule: ethernet_one_gbe_skarab_axi
  wire wbm_err_i;
  wire [38:0] wbs_ack_i;
  wire [63:0] wbs_adr_o;
  wire [38:0] wbs_cyc_o;
  wire [1247:0] wbs_dat_i;
  wire [31:0] wbs_dat_o;
  wire [38:0] wbs_err_i;
  wire [3:0] wbs_sel_o;
  wire [38:0] wbs_stb_o;
  wire wbs_we_o;
  // xsg: SKARAB
  wire user_clk;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // bram: d3/ss/bram
  wb_bram #(
    .LOG_USER_WIDTH(7),
    .N_REGISTERS(0),
    .USER_ADDR_BITS(13)
  ) ethernet_one_gbe_skarab_axi_d3_ss_bram (
    .user_addr(ethernet_one_gbe_skarab_axi_d3_ss_bram_addr),
    .user_clk(user_clk),
    .user_din(ethernet_one_gbe_skarab_axi_d3_ss_bram_data_in),
    .user_dout(ethernet_one_gbe_skarab_axi_d3_ss_bram_data_out),
    .user_we(ethernet_one_gbe_skarab_axi_d3_ss_bram_we),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_BRAM_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // bram: d4/ss/bram
  wb_bram #(
    .LOG_USER_WIDTH(7),
    .N_REGISTERS(0),
    .USER_ADDR_BITS(13)
  ) ethernet_one_gbe_skarab_axi_d4_ss_bram (
    .user_addr(ethernet_one_gbe_skarab_axi_d4_ss_bram_addr),
    .user_clk(user_clk),
    .user_din(ethernet_one_gbe_skarab_axi_d4_ss_bram_data_in),
    .user_dout(ethernet_one_gbe_skarab_axi_d4_ss_bram_data_out),
    .user_we(ethernet_one_gbe_skarab_axi_d4_ss_bram_we),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_BRAM_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // bram: d5/ss/bram
  wb_bram #(
    .LOG_USER_WIDTH(7),
    .N_REGISTERS(0),
    .USER_ADDR_BITS(13)
  ) ethernet_one_gbe_skarab_axi_d5_ss_bram (
    .user_addr(ethernet_one_gbe_skarab_axi_d5_ss_bram_addr),
    .user_clk(user_clk),
    .user_din(ethernet_one_gbe_skarab_axi_d5_ss_bram_data_in),
    .user_dout(ethernet_one_gbe_skarab_axi_d5_ss_bram_data_out),
    .user_we(ethernet_one_gbe_skarab_axi_d5_ss_bram_we),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_BRAM_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // bram: pkt_ctrs1/ss/bram
  wb_bram #(
    .LOG_USER_WIDTH(5),
    .N_REGISTERS(0),
    .USER_ADDR_BITS(16)
  ) ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram (
    .user_addr(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_addr),
    .user_clk(user_clk),
    .user_din(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_in),
    .user_dout(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_out),
    .user_we(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_we),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_BRAM_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // bram: pkt_ctrs_compare1/ss/bram
  wb_bram #(
    .LOG_USER_WIDTH(6),
    .N_REGISTERS(0),
    .USER_ADDR_BITS(13)
  ) ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram (
    .user_addr(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_addr),
    .user_clk(user_clk),
    .user_din(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_in),
    .user_dout(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_out),
    .user_we(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_we),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_BRAM_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // onegbe: tx_one_gbe
  // ethernet_one_gbe_skarab_axi_tx_one_gbe
  one_gbe #(
    .FABRIC_ENABLE(1'd1),
    .FABRIC_GATEWAY(8'd1),
    .FABRIC_IP(32'd3232246026),
    .FABRIC_MAC(48'd20015998343868),
    .FABRIC_MC_RECV_IP(32'hFFFFFFFF),
    .FABRIC_MC_RECV_IP_MASK(32'hFFFFFFFF),
    .FABRIC_NETMASK(32'd256),
    .FABRIC_PORT(16'd4321)
  ) ethernet_one_gbe_skarab_axi_tx_one_gbe (
    .ONE_GBE_MGTREFCLK_N(ONE_GBE_MGTREFCLK_N),
    .ONE_GBE_MGTREFCLK_P(ONE_GBE_MGTREFCLK_P),
    .ONE_GBE_RESET_N(ONE_GBE_RESET_N),
    .ONE_GBE_SGMII_RX_N(ONE_GBE_SGMII_RX_N),
    .ONE_GBE_SGMII_RX_P(ONE_GBE_SGMII_RX_P),
    .ONE_GBE_SGMII_TX_N(ONE_GBE_SGMII_TX_N),
    .ONE_GBE_SGMII_TX_P(ONE_GBE_SGMII_TX_P),
    .gbe_if_present(gbe_if_present),
    .gbe_link_up(gbe_link_up),
    .gbe_phy_up(gbe_link_up),
    .gbe_status_vector(gbe_status_vector),
    .gmii_reset_done_o(gmii_reset_done),
    .gmii_rx_ack(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_ack),
    .gmii_rx_bad_frame(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_badframe),
    .gmii_rx_data(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_data),
    .gmii_rx_end_of_frame(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_eof),
    .gmii_rx_overrun(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_overrun),
    .gmii_rx_source_ip(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcip),
    .gmii_rx_source_port(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcport),
    .gmii_rx_valid(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_dvld),
    .gmii_tx_afull(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_afull),
    .gmii_tx_data(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_data),
    .gmii_tx_dest_ip(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destip),
    .gmii_tx_dest_port(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destport),
    .gmii_tx_end_of_frame(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_eof),
    .gmii_tx_overflow(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_overflow),
    .gmii_tx_valid(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_dvld),
    .host_reset(host_reset_o),
    .sync_gmii_fpga_rst(sync_gmii_fpga_rst),
    .sys_clk(board_clk),
    .sys_rst(board_clk_rst),
    .user_clk(user_clk),
    .user_rst(user_rst),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_ONE_GBE_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // skarab: SKARAB
  skarab_infr #(
    .DIVCLK(14),
    .DIVIDE(3.0),
    .MULTIPLY(62.0)
  ) skarab_infr (
    .CONFIG_IO_0(CONFIG_IO_0),
    .CONFIG_IO_1(CONFIG_IO_1),
    .CONFIG_IO_10(CONFIG_IO_10),
    .CONFIG_IO_11(CONFIG_IO_11),
    .CONFIG_IO_2(CONFIG_IO_2),
    .CONFIG_IO_3(CONFIG_IO_3),
    .CONFIG_IO_4(CONFIG_IO_4),
    .CONFIG_IO_5(CONFIG_IO_5),
    .CONFIG_IO_6(CONFIG_IO_6),
    .CONFIG_IO_7(CONFIG_IO_7),
    .CONFIG_IO_8(CONFIG_IO_8),
    .CONFIG_IO_9(CONFIG_IO_9),
    .CPU_PWR_BTN_N(CPU_PWR_BTN_N),
    .CPU_PWR_OK(CPU_PWR_OK),
    .CPU_SUS_S3_N(CPU_SUS_S3_N),
    .CPU_SUS_S4_N(CPU_SUS_S4_N),
    .CPU_SUS_S5_N(CPU_SUS_S5_N),
    .CPU_SUS_STAT_N(CPU_SUS_STAT_N),
    .CPU_SYS_RESET_N(CPU_SYS_RESET_N),
    .DEBUG_UART_RX(DEBUG_UART_RX),
    .DEBUG_UART_TX(DEBUG_UART_TX),
    .EMCCLK(EMCCLK),
    .EMCCLK_FIX(EMCCLK_FIX),
    .FAN_CONT_ALERT_N(FAN_CONT_ALERT_N),
    .FAN_CONT_FAULT_N(FAN_CONT_FAULT_N),
    .FAN_CONT_RST_N(FAN_CONT_RST_N),
    .FLASH_A(FLASH_A),
    .FLASH_ADV_N(FLASH_ADV_N),
    .FLASH_CS_N(FLASH_CS_N),
    .FLASH_DQ(FLASH_DQ),
    .FLASH_OE_N(FLASH_OE_N),
    .FLASH_RS0(FLASH_RS0),
    .FLASH_RS1(FLASH_RS1),
    .FLASH_WAIT(FLASH_WAIT),
    .FLASH_WE_N(FLASH_WE_N),
    .FPGA_ATX_PSU_KILL(FPGA_ATX_PSU_KILL),
    .FPGA_EMCCLK2(FPGA_EMCCLK2),
    .FPGA_REFCLK_BUF0_N(FPGA_REFCLK_BUF0_N),
    .FPGA_REFCLK_BUF0_P(FPGA_REFCLK_BUF0_P),
    .FPGA_REFCLK_BUF1_N(FPGA_REFCLK_BUF1_N),
    .FPGA_REFCLK_BUF1_P(FPGA_REFCLK_BUF1_P),
    .FPGA_RESET_N(FPGA_RESET_N),
    .GBE_INT_N(ONE_GBE_INT_N),
    .GND(GND),
    .I2C_RESET_FPGA(I2C_RESET_FPGA),
    .I2C_SCL_FPGA(I2C_SCL_FPGA),
    .I2C_SDA_FPGA(I2C_SDA_FPGA),
    .MEZZ0_ID(mez0_id),
    .MEZZ0_INIT_DONE(mez0_init_done),
    .MEZZ0_POST_OK(mez0_post_ok),
    .MEZZ0_PRESENT(mez0_present),
    .MEZZ0_SCL_IN(mez0_scl_out),
    .MEZZ0_SCL_OUT(mez0_scl_in),
    .MEZZ0_SDA_IN(mez0_sda_out),
    .MEZZ0_SDA_OUT(mez0_sda_in),
    .MEZZ1_ID(mez1_id),
    .MEZZ1_INIT_DONE(mez1_init_done),
    .MEZZ1_POST_OK(mez1_post_ok),
    .MEZZ1_PRESENT(mez1_present),
    .MEZZ1_SCL_IN(mez1_scl_out),
    .MEZZ1_SCL_OUT(mez1_scl_in),
    .MEZZ1_SDA_IN(mez1_sda_out),
    .MEZZ1_SDA_OUT(mez1_sda_in),
    .MEZZ2_ID(mez2_id),
    .MEZZ2_INIT_DONE(mez2_init_done),
    .MEZZ2_POST_OK(mez2_post_ok),
    .MEZZ2_PRESENT(mez2_present),
    .MEZZ2_SCL_IN(mez2_scl_out),
    .MEZZ2_SCL_OUT(mez2_scl_in),
    .MEZZ2_SDA_IN(mez2_sda_out),
    .MEZZ2_SDA_OUT(mez2_sda_in),
    .MEZZANINE_0_ENABLE_N(MEZZANINE_0_ENABLE_N),
    .MEZZANINE_0_FAULT_N(MEZZANINE_0_FAULT_N),
    .MEZZANINE_0_INT_N(MEZZANINE_0_INT_N),
    .MEZZANINE_0_ONE_WIRE(MEZZANINE_0_ONE_WIRE),
    .MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N(MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N),
    .MEZZANINE_0_PRESENT_N(MEZZANINE_0_PRESENT_N),
    .MEZZANINE_0_SCL_FPGA(MEZZANINE_0_SCL_FPGA),
    .MEZZANINE_0_SDA_FPGA(MEZZANINE_0_SDA_FPGA),
    .MEZZANINE_1_ENABLE_N(MEZZANINE_1_ENABLE_N),
    .MEZZANINE_1_FAULT_N(MEZZANINE_1_FAULT_N),
    .MEZZANINE_1_INT_N(MEZZANINE_1_INT_N),
    .MEZZANINE_1_ONE_WIRE(MEZZANINE_1_ONE_WIRE),
    .MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N(MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N),
    .MEZZANINE_1_PRESENT_N(MEZZANINE_1_PRESENT_N),
    .MEZZANINE_1_SCL_FPGA(MEZZANINE_1_SCL_FPGA),
    .MEZZANINE_1_SDA_FPGA(MEZZANINE_1_SDA_FPGA),
    .MEZZANINE_2_ENABLE_N(MEZZANINE_2_ENABLE_N),
    .MEZZANINE_2_FAULT_N(MEZZANINE_2_FAULT_N),
    .MEZZANINE_2_INT_N(MEZZANINE_2_INT_N),
    .MEZZANINE_2_ONE_WIRE(MEZZANINE_2_ONE_WIRE),
    .MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N(MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N),
    .MEZZANINE_2_PRESENT_N(MEZZANINE_2_PRESENT_N),
    .MEZZANINE_2_SCL_FPGA(MEZZANINE_2_SCL_FPGA),
    .MEZZANINE_2_SDA_FPGA(MEZZANINE_2_SDA_FPGA),
    .MEZZANINE_3_CLK_SEL(MEZZANINE_3_CLK_SEL),
    .MEZZANINE_3_ENABLE_N(MEZZANINE_3_ENABLE_N),
    .MEZZANINE_3_FAULT_N(MEZZANINE_3_FAULT_N),
    .MEZZANINE_3_INT_N(MEZZANINE_3_INT_N),
    .MEZZANINE_3_ONE_WIRE(MEZZANINE_3_ONE_WIRE),
    .MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N(MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N),
    .MEZZANINE_3_PRESENT_N(MEZZANINE_3_PRESENT_N),
    .MEZZANINE_3_RESET(MEZZANINE_3_RESET),
    .MEZZANINE_3_SCL_FPGA(MEZZANINE_3_SCL_FPGA),
    .MEZZANINE_3_SDA_FPGA(MEZZANINE_3_SDA_FPGA),
    .MEZZANINE_COMBINED_FAULT(MEZZANINE_COMBINED_FAULT),
    .MONITOR_ALERT_N(MONITOR_ALERT_N),
    .ONE_GBE_LINK(ONE_GBE_LINK),
    .ONE_WIRE_EEPROM(ONE_WIRE_EEPROM),
    .ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N(ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N),
    .PCIE_RST_N(PCIE_RST_N),
    .SPARTAN_CLK(SPARTAN_CLK),
    .SPI_CLK(SPI_CLK),
    .SPI_CSB(SPI_CSB),
    .SPI_MISO(SPI_MISO),
    .SPI_MOSI(SPI_MOSI),
    .USB_FPGA(USB_FPGA),
    .USB_I2C_CTRL(USB_I2C_CTRL),
    .USB_UART_RXD(USB_UART_RXD),
    .USB_UART_TXD(USB_UART_TXD),
    .WB_SLV_ACK_O_top(wbm_ack_i),
    .WB_SLV_ADR_I_top(wbm_adr_o),
    .WB_SLV_CLK_I_top(wb_clk_i),
    .WB_SLV_CYC_I_top(wbm_cyc_o),
    .WB_SLV_DAT_I_top(wbm_dat_o),
    .WB_SLV_DAT_O_top(wbm_dat_i),
    .WB_SLV_RST_I_top(wb_rst_i),
    .WB_SLV_SEL_I_top(wbm_sel_o),
    .WB_SLV_STB_I_top(wbm_stb_o),
    .WB_SLV_WE_I_top(wbm_we_o),
    .board_clk_o(board_clk),
    .board_clk_rst_o(board_clk_rst),
    .dsp_leds_i(dsp_leds_i),
    .fgbe_if_0_present(fgbe_if_0_present),
    .fgbe_if_1_present(fgbe_if_1_present),
    .fgbe_if_2_present(fgbe_if_2_present),
    .fgbe_if_3_present(fgbe_if_3_present),
    .fgbe_phy_rx_up_0(fgbe_phy_rx_up_0),
    .fgbe_phy_rx_up_1(fgbe_phy_rx_up_1),
    .fgbe_phy_rx_up_2(fgbe_phy_rx_up_2),
    .fgbe_phy_rx_up_3(fgbe_phy_rx_up_3),
    .fpga_leds_o(FPGA_LEDS),
    .gbe_if_present(gbe_if_present),
    .gbe_phy_up(gbe_link_up),
    .gbe_status_vector(gbe_status_vector),
    .gmii_clk(gmii_clk),
    .gmii_reset_done(gmii_reset_done),
    .hmc_clk_o(hmc_clk),
    .hmc_rst_o(hmc_rst),
    .qsfp_gtrefclk(qsfp_gtrefclk_0),
    .qsfp_soft_reset_0(qsfp_soft_reset_0),
    .qsfp_soft_reset_1(qsfp_soft_reset_1),
    .qsfp_soft_reset_2(qsfp_soft_reset_2),
    .qsfp_soft_reset_3(qsfp_soft_reset_3),
    .sync_gmii_fpga_rst_o(sync_gmii_fpga_rst),
    .user_clk_o(sys_clk),
    .user_rst_o(sys_rst),
    .xlgmii_rxled_0(xlgmii_rxled_0),
    .xlgmii_rxled_1(xlgmii_rxled_1),
    .xlgmii_rxled_2(xlgmii_rxled_2),
    .xlgmii_rxled_3(xlgmii_rxled_3),
    .xlgmii_txled_0(xlgmii_txled_0),
    .xlgmii_txled_1(xlgmii_txled_1),
    .xlgmii_txled_2(xlgmii_txled_2),
    .xlgmii_txled_3(xlgmii_txled_3)
  );

  // sw_reg: addr_data_fifo
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_addr_data_fifo (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_addr_data_fifo_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_FIFO_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: addr_data_gbe
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_addr_data_gbe (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_addr_data_gbe_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ADDR_DATA_GBE_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: clk_mhz
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_clk_mhz (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_clk_mhz_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_CLK_MHZ_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d3/ss/ctrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_d3_ss_ctrl (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_d3_ss_ctrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_CTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d3/ss/status
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_d3_ss_status (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_d3_ss_status_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D3_SS_STATUS_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d4/ss/ctrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_d4_ss_ctrl (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_d4_ss_ctrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_CTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d4/ss/status
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_d4_ss_status (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_d4_ss_status_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D4_SS_STATUS_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d5/ss/ctrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_d5_ss_ctrl (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_d5_ss_ctrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_CTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: d5/ss/status
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_d5_ss_status (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_d5_ss_status_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_D5_SS_STATUS_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: data_rx_valmir
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_data_rx_valmir (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_data_rx_valmir_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_DATA_RX_VALMIR_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: debug_rx_data_mem_fifo
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_debug_rx_data_mem_fifo (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_debug_rx_data_mem_fifo_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_FIFO_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: debug_rx_data_mem_gbe
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_debug_rx_data_mem_gbe (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_debug_rx_data_mem_gbe_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_DEBUG_RX_DATA_MEM_GBE_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_marker1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_marker1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_marker1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_MARKER1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_pkt_ctr1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_pkt_ctr1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_pkt_ctr1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_pkt_ctr_step1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_pkt_ctr_step1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_pkt_ctr_step1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_PKT_CTR_STEP1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_ramp1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_ramp1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_ramp1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_RAMP1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_valid_raw1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_valid_raw1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_valid_raw1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_VALID_RAW1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: err_walk1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_err_walk1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_err_walk1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_ERR_WALK1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: pkt_ctrs1/ss/ctrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_ctrl (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_ctrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_CTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: pkt_ctrs1/ss/status
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_status (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_status_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS1_SS_STATUS_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: pkt_ctrs_compare1/ss/ctrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_ctrl (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_ctrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_CTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: pkt_ctrs_compare1/ss/status
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_status (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_status_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_PKT_CTRS_COMPARE1_SS_STATUS_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: read_gbe_or_fifo
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_read_gbe_or_fifo (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_read_gbe_or_fifo_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_READ_GBE_OR_FIFO_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: rx_badframe1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_rx_badframe1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_rx_badframe1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_BADFRAME1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: rx_control1
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_rx_control1 (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_rx_control1_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_CONTROL1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: rx_eof1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_rx_eof1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_rx_eof1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_EOF1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: rx_overrun1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_rx_overrun1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_rx_overrun1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_OVERRUN1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: rx_valid1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_rx_valid1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_rx_valid1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_RX_VALID1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: tx_afull1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_tx_afull1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_tx_afull1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_AFULL1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: tx_control
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) ethernet_one_gbe_skarab_axi_tx_control (
    .user_clk(user_clk),
    .user_data_out(ethernet_one_gbe_skarab_axi_tx_control_user_data_out),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_CONTROL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: tx_overflow1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_tx_overflow1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_tx_overflow1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_TX_OVERFLOW1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sw_reg: vaild_rx_valmir1
  wb_register_simulink2ppc  ethernet_one_gbe_skarab_axi_vaild_rx_valmir1 (
    .user_clk(user_clk),
    .user_data_in(ethernet_one_gbe_skarab_axi_vaild_rx_valmir1_user_data_in),
    .wb_ack_o(wbs_ack_i[ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0+1)*32-1:(ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0)*32]),
    .wb_err_o(wbs_err_i[ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ETHERNET_ONE_GBE_SKARAB_AXI_VAILD_RX_VALMIR1_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sys_block: SKARAB
  ethernet_one_gbe_skarab_axi  ethernet_one_gbe_skarab_axi_inst (
    .clk(user_clk),
    .ethernet_one_gbe_skarab_axi_addr_data_fifo_user_data_out(ethernet_one_gbe_skarab_axi_addr_data_fifo_user_data_out),
    .ethernet_one_gbe_skarab_axi_addr_data_gbe_user_data_out(ethernet_one_gbe_skarab_axi_addr_data_gbe_user_data_out),
    .ethernet_one_gbe_skarab_axi_d3_ss_bram_addr(ethernet_one_gbe_skarab_axi_d3_ss_bram_addr),
    .ethernet_one_gbe_skarab_axi_d3_ss_bram_data_in(ethernet_one_gbe_skarab_axi_d3_ss_bram_data_in),
    .ethernet_one_gbe_skarab_axi_d3_ss_bram_data_out(ethernet_one_gbe_skarab_axi_d3_ss_bram_data_out),
    .ethernet_one_gbe_skarab_axi_d3_ss_bram_we(ethernet_one_gbe_skarab_axi_d3_ss_bram_we),
    .ethernet_one_gbe_skarab_axi_d3_ss_status_user_data_in(ethernet_one_gbe_skarab_axi_d3_ss_status_user_data_in),
    .ethernet_one_gbe_skarab_axi_d4_ss_bram_addr(ethernet_one_gbe_skarab_axi_d4_ss_bram_addr),
    .ethernet_one_gbe_skarab_axi_d4_ss_bram_data_in(ethernet_one_gbe_skarab_axi_d4_ss_bram_data_in),
    .ethernet_one_gbe_skarab_axi_d4_ss_bram_data_out(ethernet_one_gbe_skarab_axi_d4_ss_bram_data_out),
    .ethernet_one_gbe_skarab_axi_d4_ss_bram_we(ethernet_one_gbe_skarab_axi_d4_ss_bram_we),
    .ethernet_one_gbe_skarab_axi_d4_ss_status_user_data_in(ethernet_one_gbe_skarab_axi_d4_ss_status_user_data_in),
    .ethernet_one_gbe_skarab_axi_d5_ss_bram_addr(ethernet_one_gbe_skarab_axi_d5_ss_bram_addr),
    .ethernet_one_gbe_skarab_axi_d5_ss_bram_data_in(ethernet_one_gbe_skarab_axi_d5_ss_bram_data_in),
    .ethernet_one_gbe_skarab_axi_d5_ss_bram_data_out(ethernet_one_gbe_skarab_axi_d5_ss_bram_data_out),
    .ethernet_one_gbe_skarab_axi_d5_ss_bram_we(ethernet_one_gbe_skarab_axi_d5_ss_bram_we),
    .ethernet_one_gbe_skarab_axi_d5_ss_status_user_data_in(ethernet_one_gbe_skarab_axi_d5_ss_status_user_data_in),
    .ethernet_one_gbe_skarab_axi_data_rx_valmir_user_data_in(ethernet_one_gbe_skarab_axi_data_rx_valmir_user_data_in),
    .ethernet_one_gbe_skarab_axi_debug_rx_data_mem_fifo_user_data_in(ethernet_one_gbe_skarab_axi_debug_rx_data_mem_fifo_user_data_in),
    .ethernet_one_gbe_skarab_axi_debug_rx_data_mem_gbe_user_data_in(ethernet_one_gbe_skarab_axi_debug_rx_data_mem_gbe_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_marker1_user_data_in(ethernet_one_gbe_skarab_axi_err_marker1_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_pkt_ctr1_user_data_in(ethernet_one_gbe_skarab_axi_err_pkt_ctr1_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_pkt_ctr_step1_user_data_in(ethernet_one_gbe_skarab_axi_err_pkt_ctr_step1_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_ramp1_user_data_in(ethernet_one_gbe_skarab_axi_err_ramp1_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_valid_raw1_user_data_in(ethernet_one_gbe_skarab_axi_err_valid_raw1_user_data_in),
    .ethernet_one_gbe_skarab_axi_err_walk1_user_data_in(ethernet_one_gbe_skarab_axi_err_walk1_user_data_in),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_addr(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_addr),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_in),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_out(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_data_out),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_we(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_bram_we),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_status_user_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs1_ss_status_user_data_in),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_addr(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_addr),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_in),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_out(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_data_out),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_we(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_bram_we),
    .ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_status_user_data_in(ethernet_one_gbe_skarab_axi_pkt_ctrs_compare1_ss_status_user_data_in),
    .ethernet_one_gbe_skarab_axi_read_gbe_or_fifo_user_data_out(ethernet_one_gbe_skarab_axi_read_gbe_or_fifo_user_data_out),
    .ethernet_one_gbe_skarab_axi_rx_badframe1_user_data_in(ethernet_one_gbe_skarab_axi_rx_badframe1_user_data_in),
    .ethernet_one_gbe_skarab_axi_rx_control1_user_data_out(ethernet_one_gbe_skarab_axi_rx_control1_user_data_out),
    .ethernet_one_gbe_skarab_axi_rx_eof1_user_data_in(ethernet_one_gbe_skarab_axi_rx_eof1_user_data_in),
    .ethernet_one_gbe_skarab_axi_rx_overrun1_user_data_in(ethernet_one_gbe_skarab_axi_rx_overrun1_user_data_in),
    .ethernet_one_gbe_skarab_axi_rx_valid1_user_data_in(ethernet_one_gbe_skarab_axi_rx_valid1_user_data_in),
    .ethernet_one_gbe_skarab_axi_tx_afull1_user_data_in(ethernet_one_gbe_skarab_axi_tx_afull1_user_data_in),
    .ethernet_one_gbe_skarab_axi_tx_control_user_data_out(ethernet_one_gbe_skarab_axi_tx_control_user_data_out),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_dbg_data(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_dbg_data),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_dbg_dvld(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_dbg_dvld),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_ack(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_ack),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_badframe(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_badframe),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_data(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_data),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_dvld(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_dvld),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_eof(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_eof),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_overrun(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_overrun),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_rst(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_rst),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcip(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcip),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcport(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_rx_srcport),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_afull(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_afull),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_data(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_data),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destip(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destip),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destport(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_destport),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_dvld(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_dvld),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_eof(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_eof),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_overflow(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_overflow),
    .ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_rst(ethernet_one_gbe_skarab_axi_tx_one_gbe_app_tx_rst),
    .ethernet_one_gbe_skarab_axi_tx_overflow1_user_data_in(ethernet_one_gbe_skarab_axi_tx_overflow1_user_data_in),
    .ethernet_one_gbe_skarab_axi_vaild_rx_valmir1_user_data_in(ethernet_one_gbe_skarab_axi_vaild_rx_valmir1_user_data_in),
    .skarab_tx_1gbe_tx_rx_valmir_clk_mhz_user_data_in(skarab_tx_1gbe_tx_rx_valmir_clk_mhz_user_data_in),
    .skarab_tx_1gbe_tx_rx_valmir_d3_ss_ctrl_user_data_out(skarab_tx_1gbe_tx_rx_valmir_d3_ss_ctrl_user_data_out),
    .skarab_tx_1gbe_tx_rx_valmir_d4_ss_ctrl_user_data_out(skarab_tx_1gbe_tx_rx_valmir_d4_ss_ctrl_user_data_out),
    .skarab_tx_1gbe_tx_rx_valmir_d5_ss_ctrl_user_data_out(skarab_tx_1gbe_tx_rx_valmir_d5_ss_ctrl_user_data_out),
    .skarab_tx_1gbe_tx_rx_valmir_pkt_ctrs1_ss_ctrl_user_data_out(skarab_tx_1gbe_tx_rx_valmir_pkt_ctrs1_ss_ctrl_user_data_out),
    .skarab_tx_1gbe_tx_rx_valmir_pkt_ctrs_compare1_ss_ctrl_user_data_out(skarab_tx_1gbe_tx_rx_valmir_pkt_ctrs_compare1_ss_ctrl_user_data_out)
  );


  sys_block #(
    .BOARD_ID(3),
    .REV_MAJ(2),
    .REV_MIN(0),
    .REV_RCS(1)
  ) sys_block_inst (
    .user_clk(user_clk),
    .wb_ack_o(wbs_ack_i[SYS_BLOCK_INST_WBID0]),
    .wb_adr_i(wbs_adr_o[(1+1)*32-1:(1)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[SYS_BLOCK_INST_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(SYS_BLOCK_INST_WBID0+1)*32-1:(SYS_BLOCK_INST_WBID0)*32]),
    .wb_err_o(wbs_err_i[SYS_BLOCK_INST_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[SYS_BLOCK_INST_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // usermodule: ethernet_one_gbe_skarab_axi
  wbs_master_arbiter #(
    .N_SLAVES(N_WB_SLAVES),
    .N_SUB_ARBS(N_SUB_ARBS),
    .SLAVE_ADDR(SLAVE_ADDR),
    .SLAVE_HIGH(SLAVE_HIGH),
    .TIMEOUT(1024)
  ) wbs_arbiter_inst (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wbm_ack_o(wbm_ack_i),
    .wbm_adr_i(wbm_adr_o),
    .wbm_cyc_i(wbm_cyc_o),
    .wbm_dat_i(wbm_dat_o),
    .wbm_dat_o(wbm_dat_i),
    .wbm_err_o(wbm_err_i),
    .wbm_sel_i(wbm_sel_o),
    .wbm_stb_i(wbm_stb_o),
    .wbm_we_i(wbm_we_o),
    .wbs_ack_i(wbs_ack_i),
    .wbs_adr_o(wbs_adr_o),
    .wbs_cyc_o(wbs_cyc_o),
    .wbs_dat_i(wbs_dat_i),
    .wbs_dat_o(wbs_dat_o),
    .wbs_err_i(wbs_err_i),
    .wbs_sel_o(wbs_sel_o),
    .wbs_stb_o(wbs_stb_o),
    .wbs_we_o(wbs_we_o)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // xsg: SKARAB
  assign user_clk = sys_clk;


endmodule