#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jun 20 21:36:06 -03 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_func_synth -key {Post-Synthesis:sim_1:Functional:tb} -tclbatch tb.tcl -view /home/valmyrsilva07/skrab_one/tb_behav.wcfg -log simulate.log"
xsim tb_func_synth -key {Post-Synthesis:sim_1:Functional:tb} -tclbatch tb.tcl -view /home/valmyrsilva07/skrab_one/tb_behav.wcfg -log simulate.log

