
function gbe_control_config(this_block)

  % Revision History:
  %
  %   03-Jun-2026  (18:01 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/gbe_contro_beta_v2.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('gbe_control');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('nrst');
  this_block.addSimulinkInport('decimation_factor');
  this_block.addSimulinkInport('tx_package_len');
  this_block.addSimulinkInport('tx_en');

  this_block.addSimulinkOutport('tx_val');
  this_block.addSimulinkOutport('tx_eof');
  this_block.addSimulinkOutport('tx_data');
  this_block.addSimulinkOutport('ena_dec_tmp');
  this_block.addSimulinkOutport('counter_tmp');
  this_block.addSimulinkOutport('tx_valid_package');

  tx_val_port = this_block.port('tx_val');
  tx_val_port.setType('UFix_4_0');
  tx_eof_port = this_block.port('tx_eof');
  tx_eof_port.setType('UFix_1_0');
  tx_eof_port.useHDLVector(false);
  tx_data_port = this_block.port('tx_data');
  tx_data_port.setType('UFix_8_0');
  ena_dec_tmp_port = this_block.port('ena_dec_tmp');
  ena_dec_tmp_port.setType('UFix_1_0');
  ena_dec_tmp_port.useHDLVector(false);
  counter_tmp_port = this_block.port('counter_tmp');
  counter_tmp_port.setType('UFix_32_0');
  tx_valid_package_port = this_block.port('tx_valid_package');
  tx_valid_package_port.setType('UFix_1_0');
  tx_valid_package_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('nrst').width ~= 1);
      this_block.setError('Input data type for port "nrst" must have width=1.');
    end

    this_block.port('nrst').useHDLVector(false);

    if (this_block.port('decimation_factor').width ~= 32);
      this_block.setError('Input data type for port "decimation_factor" must have width=32.');
    end

    if (this_block.port('tx_package_len').width ~= 10);
      this_block.setError('Input data type for port "tx_package_len" must have width=10.');
    end

    if (this_block.port('tx_en').width ~= 1);
      this_block.setError('Input data type for port "tx_en" must have width=1.');
    end

    this_block.port('tx_en').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/gbe_contro_beta_v2.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

