
function gbe_control_config(this_block)

  % Revision History:
  %
  %   16-Jun-2026  (01:31 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/gbe_control.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('gbe_control');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('a_sync_nrst');
  this_block.addSimulinkInport('decimation_factor');
  this_block.addSimulinkInport('tx_package_len');
  this_block.addSimulinkInport('rx_valid');
  this_block.addSimulinkInport('rx_data');
  this_block.addSimulinkInport('rx_eof');
  this_block.addSimulinkInport('debug_rx_addr_data');
  this_block.addSimulinkInport('debug_ena_mux');

  this_block.addSimulinkOutport('tx_valid');
  this_block.addSimulinkOutport('tx_eof');
  this_block.addSimulinkOutport('tx_data');
  this_block.addSimulinkOutport('debug_rx_data');
  this_block.addSimulinkOutport('debug_rx_data_ff1');
  this_block.addSimulinkOutport('debug_rx_data_ff2');
  this_block.addSimulinkOutport('debug_rx_data_ff3');
  this_block.addSimulinkOutport('debug_start_frame_transmission');
  this_block.addSimulinkOutport('debug_start_frame_reception');
  this_block.addSimulinkOutport('debug_current_state');

  tx_valid_port = this_block.port('tx_valid');
  tx_valid_port.setType('UFix_4_0');
  tx_eof_port = this_block.port('tx_eof');
  tx_eof_port.setType('UFix_1_0');
  tx_eof_port.useHDLVector(false);
  tx_data_port = this_block.port('tx_data');
  tx_data_port.setType('UFix_8_0');
  debug_rx_data_port = this_block.port('debug_rx_data');
  debug_rx_data_port.setType('UFix_8_0');
  debug_rx_data_ff1_port = this_block.port('debug_rx_data_ff1');
  debug_rx_data_ff1_port.setType('UFix_8_0');
  debug_rx_data_ff2_port = this_block.port('debug_rx_data_ff2');
  debug_rx_data_ff2_port.setType('UFix_8_0');
  debug_rx_data_ff3_port = this_block.port('debug_rx_data_ff3');
  debug_rx_data_ff3_port.setType('UFix_8_0');
  debug_start_frame_transmission_port = this_block.port('debug_start_frame_transmission');
  debug_start_frame_transmission_port.setType('UFix_1_0');
  debug_start_frame_transmission_port.useHDLVector(false);
  debug_start_frame_reception_port = this_block.port('debug_start_frame_reception');
  debug_start_frame_reception_port.setType('UFix_1_0');
  debug_start_frame_reception_port.useHDLVector(false);
  debug_current_state_port = this_block.port('debug_current_state');
  debug_current_state_port.setType('UFix_3_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('a_sync_nrst').width ~= 1);
      this_block.setError('Input data type for port "a_sync_nrst" must have width=1.');
    end

    this_block.port('a_sync_nrst').useHDLVector(false);

    if (this_block.port('decimation_factor').width ~= 32);
      this_block.setError('Input data type for port "decimation_factor" must have width=32.');
    end

    if (this_block.port('tx_package_len').width ~= 10);
      this_block.setError('Input data type for port "tx_package_len" must have width=10.');
    end

    if (this_block.port('rx_valid').width ~= 1);
      this_block.setError('Input data type for port "rx_valid" must have width=1.');
    end

    this_block.port('rx_valid').useHDLVector(false);

    if (this_block.port('rx_data').width ~= 8);
      this_block.setError('Input data type for port "rx_data" must have width=8.');
    end

    if (this_block.port('rx_eof').width ~= 1);
      this_block.setError('Input data type for port "rx_eof" must have width=1.');
    end

    this_block.port('rx_eof').useHDLVector(false);

    if (this_block.port('debug_rx_addr_data').width ~= 11);
      this_block.setError('Input data type for port "debug_rx_addr_data" must have width=11.');
    end

    if (this_block.port('debug_ena_mux').width ~= 2);
      this_block.setError('Input data type for port "debug_ena_mux" must have width=1.');
    end

    this_block.port('debug_ena_mux').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/gbe_control.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

