
function wrapper_buffer_in_ethernet_verilog_config(this_block)

  % Revision History:
  %
  %   01-Jun-2026  (19:21 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/wrapper_buffer_in_ethernet_verilog.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('wrapper_buffer_in_ethernet_verilog');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('a_sync_nrst');
  this_block.addSimulinkInport('in_valid_rx');
  this_block.addSimulinkInport('in_data_rx_ethernet');
  this_block.addSimulinkInport('package_size');
  this_block.addSimulinkInport('addr_data');
  this_block.addSimulinkInport('data_valid_rx');
  this_block.addSimulinkInport('tx_eof');

  this_block.addSimulinkOutport('data_out_buffer');


  data_out_buffer_port = this_block.port('tx_eof');
  data_out_buffer_port.setType('UFix_1_0');


  data_out_buffer_port = this_block.port('data_out_buffer');
  data_out_buffer_port.setType('UFix_8_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('a_sync_nrst').width ~= 1);
      this_block.setError('Input data type for port "a_sync_nrst" must have width=1.');
    end

    this_block.port('a_sync_nrst').useHDLVector(false);

    if (this_block.port('in_valid_rx').width ~= 1);
      this_block.setError('Input data type for port "in_valid_rx" must have width=1.');
    end

    this_block.port('in_valid_rx').useHDLVector(false);

    if (this_block.port('in_data_rx_ethernet').width ~= 8);
      this_block.setError('Input data type for port "in_data_rx_ethernet" must have width=8.');
    end

    if (this_block.port('package_size').width ~= 10);
      this_block.setError('Input data type for port "package_size" must have width=10.');
    end

    if (this_block.port('addr_data').width ~= 8);
      this_block.setError('Input data type for port "addr_data" must have width=8.');
    end

    if (this_block.port('data_valid_rx').width ~= 1);
      this_block.setError('Input data type for port "data_valid_rx" must have width=1.');
    end

    this_block.port('data_valid_rx').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/wrapper_buffer_in_ethernet_verilog.v');
  this_block.addFile('/home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/verilog_custom/onegbe_skarab/buffer_in_ethernet.v'); 
return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

