# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0.xci
# IP: The module: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0.xci
# IP: The module: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/valmyrsilva07/virtex7/skarab-virtex7-toolflow/fpgs/ethernet_one_gbe_skarab_control/ethernet_one_gbe_skarab_axi_fir/myproj/myproj.srcs/sources_1/ip/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0/ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ethernet_one_gbe_skarab_axi_fir_fir_compiler_v7_2_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
